### PR TITLE
FIX: Try to unpin mpich after new version available.

### PR DESCRIPTION
**Pull request by hhslepicka**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Trying to unpin after work done for https://github.com/conda-forge/mpich-feedstock/issues/56

### CODE REVIEW

**Comment by hhslepicka** [comment]
@conda-forge-admin, please rerender

**Comment by hhslepicka** [comment]
Rebased to pick up the latest release info.

**Comment by leofang** [comment]
The mpich fix is in, let's give it a shot

@conda-forge-admin, please restart ci

**Comment by hhslepicka** [comment]
@leofang it looks like it did it! Thanks for restarting CI here.

**Comment by leofang** [comment]
Cool! Perhaps you'd like to clean up the workarounds you added (`fake-bin` etc)?

**Comment by hhslepicka** [comment]
I will try to remove the fake-bin one but it was related to osx issue with `cc1` that was not found somehow.

**Comment by leofang** [comment]
Ah I see, I thought it was for fixing the OS X build. nvm then.

**Comment by hhslepicka** [comment]
@leofang for reference, the cc1 issue comes from here: https://github.com/conda-forge/gfortran_osx-64-feedstock/issues/11 and the workaround from here https://github.com/awvwgk/staged-recipes/tree/dftd4/recipes/dftd4

**Pull request merged**
